### ISSUE TITLE
dryrun mode should log selected compilers

### ISSUE THREAD

**Issue by clark2668** [ara-software/cvmfs#2]
when run in `--dryrun`, it would be helpful if the compilers it's going to use (e.g, gcc version, etc) are printed out in addition to installation locations.

**Comment by bhokansonfasig** [comment]
Good idea. I added that as a quick-and-dirty way for me to just check that the script would run at its most basic, but I'll look into making it more useful as a "true" dry run of the installation

**Comment by clark2668** [comment]
It might actually good for this to be printed out in all modes, but to the extent that the `dryrun` flag is used to ask "is this going to do what I think it's going to do", it seems like a natural place for it.

**Comment by bhokansonfasig** [comment]
Yeah, that would be easier to implement too :)
I was just looking and I could consider running make commands with [--dry-run](https://www.gnu.org/software/make/manual/html_node/Options-Summary.html) as well in this mode. Do you have thoughts on this?

**Comment by clark2668** [comment]
Do you mean run the configure commands?

**Comment by bhokansonfasig** [comment]
It does look like I'd have to run the configure commands outright in order to then have `make --dry-run` show the proper outputs

**Comment by clark2668** [comment]
I don't think that's necessary in the dryrun. just showing where it's going to install, and what dependencies it's going to try and install with should be enough I think.
