### ISSUE TITLE
dependencies are not found correctly for ROOT

### ISSUE THREAD

**Issue by clark2668** [ara-software/cvmfs#3]
ROOT does not locate the correct versions of GSL and SQLite to compile against.

Probably need to add `GSL_ROOT_DIR` and `SQLITE_ROOT` environment variables before compiling ROOT.

**Comment by bhokansonfasig** [comment]
Evidently setting `GSL_ROOT` is not sufficient, as CMake decides to ignore the environment variable:

> Environment variable GSL_ROOT is set to:
>
>    /scratch/fasig/ara.opensciencegrid.org/trunk/root_build
>
>  For compatibility, CMake is ignoring the variable.

@clark2668 's suggestion of setting `GSL_ROOT_DIR` (rather than `GSL_ROOT`) may be necessary

**Comment by bhokansonfasig** [comment]
`GSL_ROOT_DIR` looks like it would work with the default GSL finder from CMake:
https://github.com/Kitware/CMake/blob/master/Modules/FindGSL.cmake

This is overridden by the GSL finder for ROOT however, which prefers `GSL_DIR`:
https://github.com/cxx-hep/root-cern/blob/master/cmake/modules/FindGSL.cmake

Unfortunately there isn't an equivalent "hint" environment variable available for SQLite:
https://github.com/cxx-hep/root-cern/blob/master/cmake/modules/FindSqlite.cmake

So, instead I'm working on a solution using `CMAKE_PREFIX_PATH` which should tell any `find_*` command in CMake to look in that path first, forcing it to find our installed dependencies over system versions:
https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure

**Comment by clark2668** [comment]
this looks to be fixed in the latest version, as tested on the Ohio cluster. ROOT seems to be able to "find" the local installations of GSL, FFTW, and Sqlite. This is a good solution too, as it is more general than setting individual hints.
