### ISSUE TITLE
AraRoot is potentially being compiled against incorrect version of dependencies

### ISSUE THREAD

**Issue by clark2668** [ara-software/cvmfs#4]
I think AraRoot's cmake might be trying to compile against a version that is different from that used to compile everything else. I get lots of errors like this:

> CMake Warning at debugging/operating_parameters/vadj/CMakeLists.txt:7 (add_executable):
  Cannot generate a safe runtime search path for target
  estimate_sampling_speed_runList because files in some directories may
  conflict with libraries in implicit directories:

>    runtime library [libsqlite3.so.0] in /usr/lib64 may be hidden by files in:
      /fs/scratch/PAS0654/ara/osg_build_test/build_here/build/lib

>  Some of these libraries may not be found correctly.

I'm not sure the error is fatal, but sometimes this can be resolved by setting some specific variables:

> `set(FFTW_LIBRARIES "$ENV{PLATFORM_DIR}/lib/libfftw3.so.3.4.4")`
> `set(FFTW_INCLUDES "$ENV{PLATFORM_DIR}/include")`

But, that's probably a demonstration that the AraRoot CMakeLists.txt needs updating more than it is an issue with the builder.

**Comment by bhokansonfasig** [comment]
Interesting. I actually do set those lines in CMakeLists.txt for libRootFftwWrapper (since `find_package(FFTW REQUIRED)` didn't work for whatever reason). I'll look into doing the same for AraRoot then

**Comment by bhokansonfasig** [comment]
It's possible this is related to #3, will try a similar fix using `CMAKE_PREFIX_PATH` here.

**Comment by clark2668** [comment]
Like in #3, this seems to be fixed in the latest version as tested on the Ohio cluster. I suspect it was important to fix both in order to get this to work.
