### ISSUE TITLE
libAraVertex.so needs to be loaded in rootlogon.C

### ISSUE THREAD

**Issue by uzairlatif90** [ara-software/cvmfs#6]
We need to add gSystem->Load("libAraVertex.so"); to the rootlogon.C so that the newly installed AraVertex class made by Brian can be used by all the users.

**Comment by clark2668** [comment]
Silly question: where does ara_rootlogon.C get made? I don't actually see it in AraRoot...

**Comment by bhokansonfasig** [comment]
I manually added it at `cvmfs/ara.opensciencegrid.org/trunk/build/macros`, and then after installing AraRoot I edit `etc/system.rootrc` in ROOT's build directory so that Rint.Logon points to the new `ara_rootlogon.C`. Not sure if it's something that would be automatically created by AraRoot, although I guess it could be

**Comment by clark2668** [comment]
Ohh, very nice. I'm rather indifferent on this specific point... It probably makes a little more sense for `ara_rootlogon.C` to be created with `AraRoot` itself, but then again, not everyone uses that feature, so it being install specific is probably okay. what do you all think?

**Comment by bhokansonfasig** [comment]
I have no real preference. As long as it's available for the cvmfs installation, I imagine that's good enough for most people.

I'm also curious whether it makes sense to add `libAra.so`. Knowing very little about what the use case of the interactive system is, I'm not sure if AraSim stuff is useful there or not.

**Comment by clark2668** [comment]
For the time being, it might make sense to leave it in the cvmfs then.

Regarding `libAra.so`, I defer to people who use root interactively. My inclination is to not do so yet if there is no demand for it currently.

**Comment by bhokansonfasig** [comment]
Okay, for now I'll just add `libAraVertex.so` then.
