### ISSUE TITLE
Overload of ARA_UTIL_INSTALL_DIR?

### ISSUE THREAD

**Issue by clark2668** [ara-software/cvmfs#7]
Hi--I wanted to discuss something, and this seems a reasonable place to do it for documentation's sake!

I realized in the current version of cvmfs, ARA_UTIL_INSTALL_DIR actually ends up containing both the ARA libraries, like `libAraEvent.so`, as well as dependency libraries, like `libfftw3.so.3.4.4`. What do you think about splitting these up and assigning the dependencies to their own directory, like `TOOLS_DIR`, or something like that?

So there might be something like:
`ARA_UTIL_INSTALL_DIR=/cvmfs/ara.opensciencegrid.org/v1.0.0/centos7/ara_build/`
`TOOLS_DIR=/cvmfs/ara.opensciencegrid.org/v1.0.0/centos7/tools_build/`

I say this mostly out of concern that if a "power user" tries to compile their own local installation of AraRoot, but using cvmfs dependencies, then they might accidentally "pick-up" ARA stuff from the cvmfs installation. I haven't encountered this problem myself yet, but it has me wondering...

Let me know what you think

**Comment by bhokansonfasig** [comment]
That does sound like a cleaner way to handle things. I'm not sure how much effort would be needed to split things up; it's entirely possible that there's something requiring these to all be in the same place. But I think we should try separating them and see if/where it goes wrong

**Comment by clark2668** [comment]
I can confirm they are not required to be in the same place. (My local analysis installations do not have them installed in the same place.) You might have to play with the CMakeList for ROOT to get all the paths right. And you might need to watch where you do the libROOTFFTWwrapper installation.

**Comment by bhokansonfasig** [comment]
libROOTFFTWwrapper brings up an interesting issue, where do we draw the line? Is that an "ARA utility" or a "dependency"? My instinct is dependency, but as you say it may need to be in one of the directories rather than the other. So maybe it makes the decision for us

**Comment by clark2668** [comment]
if it makes the decision for us (e.g., demands to be in the ARA utility category), then we're good. if not, then I think I agree with you in putting it in the dependency category.

**Comment by bhokansonfasig** [comment]
Alright, so then the only ARA utilities would be AraRoot and AraSim, right?

**Comment by clark2668** [comment]
Yes, I think so. This way of framing the problem also gives us room to grow, if we eventually want to put a ray tracing correlator method (like radiospline, etc.) into the ARA utilities category, but want to keep a dependency isolated somewhere else.
