### ISSUE TITLE
do not install AraSim in build/bin directory

### ISSUE THREAD

**Issue by clark2668** [ara-software/cvmfs#8]
Currently the `AraSim` executable is installed in the `/cvmfs/ara.opensciencegrid.org/v1.0.0/centos7/build/bin` and the `/cvmfs/ara.opensciencegrid.org/trunk/centos7/build/bin` directories. However, AraSim needs access to some detector files that have paths that are _relative_ to the AraSim source directory (e.g., see https://github.com/ara-software/AraSim/blob/master/Detector.cc#L1025) and so if you try and execute AraSim from the `build/bin` directory, you get a cryptic "out-of-range" error:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted
```

which is really just about the fact that AraSim can't find all the support files it needs. We could solve this in AraSim by requiring the user to set an `ARA_SIM_DIR`, but for now, we should not install `AraSim` into the `build/bin` directory.

**Comment by bhokansonfasig** [comment]
Ah, I wondered if there would be a problem like that. It was with a bit of wishful thinking that I copied the executable into `build/bin`. I'll just keep it in the AraSim source directory then (along with the other executables (`readTree` and `readGeom`).

Do you have any idea whether it may work if `AraSim` was a symbolic link in the `build/bin` directory that pointed to the executable in the source directory?

**Comment by clark2668** [comment]
Okay, sounds good re: the non-installation.

I have no idea about handling it with a symlink. My instinct says it wouldn't work, but I haven't tried it....

**Comment by bhokansonfasig** [comment]
It may be relatively straightforward to test actually. Do you think you could make a symlink just in some temporary directory on the cobalts of the `AraSim` executable from the source directory and see how it behaves?

**Comment by clark2668** [comment]
Oh, good idea. I just ran a quick test with a symlink, and it still throws the following error:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted
```

so I think we're out of luck there.

**Comment by bhokansonfasig** [comment]
Okay, thanks for trying it. I'll just skip that part of the installation then

**Comment by clark2668** [comment]
Sure, happy to help. And great, thanks!
